<?php

/**
 * @file dhs_migrate.module
 * Nothing here to see.
 */

include_once('migrate_dhs.inc');

/**
 * Common mappings for the Drupal 6 node migrations.
 */
abstract class DHSNodeMigration extends DrupalNode6Migration {
  public function __construct(array $arguments) {
    parent::__construct($arguments);

    $this->addFieldMapping('field_legacy_nid', 'nid')
         ->description('We have a common field to save the D6 nid');
  }
}

class ArticleMigration extends DHSNodeMigration {
  public function __construct(array $arguments) {
    parent::__construct($arguments);

    // $this->addFieldMapping('body', 'body');

    // Note that we map migrated terms by the vocabulary ID.
    // $this->addFieldMapping('field_tagg', '1')
    //      ->sourceMigration('tags');
    // $this->addFieldMapping('field_tagg:source_type')
    //      ->defaultValue('tid');
  }
}

class AlbumMigration extends DHSNodeMigration {
  public function __construct(array $arguments) {
    parent::__construct($arguments);
  }
}

class ImageMigration extends DHSNodeMigration {
  public function __construct(array $arguments) {
    parent::__construct($arguments);
  }
}
