<?php

// /**
//  * Common mappings for the Drupal 6 node migrations.
//  */
// abstract class DHSNodeMigration extends DrupalNode6Migration {
//   public function __construct(array $arguments) {
//     print_r($arguments);
//     parent::__construct($arguments);

//     $this->addFieldMapping('field_legacy_nid', 'nid')
//          ->description('We have a common field to save the D6 nid');
//   }
// }

// class ArticleMigration extends DHSNodeMigration {
//   public function __construct(array $arguments) {
//     parent::__construct($arguments);
//   }
// }

// class AlbumMigration extends DHSNodeMigration {
//   public function __construct(array $arguments) {
//     parent::__construct($arguments);
//   }
// }

// class ImageMigration extends DHSNodeMigration {
//   public function __construct(array $arguments) {
//     parent::__construct($arguments);
//   }
// }
